version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  flaskapp:
    build:
      context: ./flask_core
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./consumer_grafos
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - flaskapp  